### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by watilde** [depjs/dep#23]
### Summary
To move to the [org](https://github.com/depjs), I'd like to have a logo. I will do something. In the case you have an idea, please let me know!

### Steps to reproduce behavior
Visit https://github.com/depjs

### Expected behavior
![oqp8ad1qshgz](https://user-images.githubusercontent.com/1716463/30201998-266a6dca-947d-11e7-96a9-e51d0e5f750e.png)

### Actual behavior
No logo!

**Comment by watilde** [comment]
Spec: https://github.com/terinjokes/StickerConstructorSpec

**Comment by kuzminadya** [comment]
Hey! What do you think of it? Just some ideas.
![screen shot 2017-09-12 at 15 35 23](https://user-images.githubusercontent.com/20212840/30329344-52765502-97d2-11e7-88e1-9af2a3226427.png)

**Comment by watilde** [comment]
@kuzminadya Heyyy great works! They look so kewl. Particularly, the third one can be easy to be realised what it's written :) Could we use a different colour for the background, like orange?

**Comment by kuzminadya** [comment]
Thank you! I've changed the last one a little bit. 
![screen shot 2017-09-13 at 23 09 10](https://user-images.githubusercontent.com/20212840/30401036-2e09d9e8-98d9-11e7-9c45-7737726605b4.png)

**Comment by watilde** [comment]
@kuzminadya Heyyy that's perfect for me <3
I just created a repository for [artwork✨](https://github.com/depjs/artwork). Let me invite you to the org!

**Comment by watilde** [comment]
https://github.com/depjs/artwork/pull/2

🎉
