### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by watilde** [depjs/dep#67]
### Summary
`dep` is used by Go already and I heard that as a pain on CI by some users.
We provide `depjs` as alias, but it's also worth thinking about new name.
+ https://github.com/depjs/dep/blob/master/package.json#L19

Drop your thought on this issue please if you have a good idea.

**Comment by jorgebucaran** [comment]
@watilde What about `nodep` or `ndep` to keep it short? 🤔

A vaguely-related, catchy-name (in the same vein of `yarn`) e.g., `clump`.

Or something cool, but unrelated like `sugarbomb`.
